### ISSUE TITLE
How to stream any type of data in addition to video frames?

### ISSUE THREAD

**Issue by RayShing** [microsoft/ringmaster#2]
Hello, I would like to ask how can I stream any type of data, such as JSON  tokens or point clouds?

**Comment by francisyyan** [comment]
It's not going to be trivial, but at a very high level, the idea is to have the sender read from a different source rather than video (https://github.com/microsoft/ringmaster/blob/main/src/app/video_sender.cc#L153), compress the data, and eventually append it to UDP's send buffer (https://github.com/microsoft/ringmaster/blob/main/src/app/encoder.cc#L222).
